version: "3.3"

services:
  web:
    build: .
    ports:
      - 8888:8888
    environment:
      - DB_URL=mongodb://db
    volumes:
      - lab:/opt/lab
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

volumes:
  db_data:
  lab:
