version: "3.3"

services:
  web:
    build: .
    ports:
      - 8888:8888
    environment:
      - DB_URL=mongodb://<username>:<password>@db
    volumes:
      - jupyter_lab:/ops/lab
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  jupyter_lab:
